[package]
name = "restp"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.4", features = ["macros"] }
serde_json = { version = "1.0.140", features = ["raw_value"] }
tokio = { version = "1.45.1", features = ["full"] }
